[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
pythonpath = . src impostor-bot
addopts = --cov=src --cov-report=term-missing --cov-config=pytest.ini

[coverage:run]
omit =
    */src/impostor-bot/discord*
    */src/impostor-bot/config.py
    */src/impostor-bot/constants.py
    */src/impostor-bot/main.py