MIN_PLAYERS = 3
STATUS_OPEN = "OPEN"
STATUS_STARTED = "STARTED"
STATUS_CANCELLED = "CANCELLED"

EMOJI_GAME = "🎭"
EMOJI_SUCCESS = "✅"
EMOJI_WARNING = "⚠️"
EMOJI_ERROR = "❌"
EMOJI_DOOR = "🚪"
EMOJI_DICE = "🎲"
EMOJI_INFO = "ℹ️"
EMOJI_LIST = "📋"
EMOJI_LOCK = "🔒"

IMPOSTOR_ROLE = "IMPOSTOR"

DEFAULT_WORD_CATEGORY = "general"