"""create game persistence schema

Revision ID: 3e88f496df61
Revises: 
Create Date: 2026-08-31 15:51:17.209118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e88f496df61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('secret_word', sa.Text(), nullable=True),
    sa.Column('impostor_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("state IN ('OPEN', 'STARTED', 'FINISHED', 'CANCELLED')", name='ck_games_state'),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id')
    )
    op.create_table('game_players',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'channel_id'], ['games.guild_id', 'games.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id', 'player_id'),
    sa.UniqueConstraint('guild_id', 'channel_id', 'position', name='uq_game_players_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_players')
    op.drop_table('games')
    # ### end Alembic commands ###
