"""persist discord lobby sessions

Revision ID: 989aad764c77
Revises: 3e88f496df61
Create Date: 2026-08-31 20:43:59.277467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989aad764c77'
down_revision: Union[str, Sequence[str], None] = '3e88f496df61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_game_sessions',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('lobby_message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'channel_id'], ['games.guild_id', 'games.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id'),
    sa.UniqueConstraint('lobby_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_game_sessions')
    # ### end Alembic commands ###
